---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shopping-service
  labels:
    app: shopping-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shopping-service
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  template:
    metadata:
      labels:
        app: shopping-service
    spec:
      containers:
      - name: shopping-service
        image: backend-ms-shopping:latest2  # Update with your image
        imagePullPolicy: Never
        ports:
        - containerPort: 8003
        env:
        - name: NODE_ENV
          value: "prod"
        - name: APP_SECRET
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: APP_SECRET
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: MONGODB_URI_SHOPPING
        - name: MSG_QUEUE_URL
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: MSG_QUEUE_URL
        - name: EXCHANGE_NAME
          valueFrom:
            configMapKeyRef:
              name: common-config
              key: EXCHANGE_NAME
        - name: PORT
          value: "8003"
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 30
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 8003
          initialDelaySeconds: 60
          periodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  name: shopping-service
  labels:
    app: shopping-service
spec:
  selector:
    app: shopping-service
  ports:
  - port: 8003
    targetPort: 8003
    protocol: TCP
  type: ClusterIP